#!/bin/bash

set -e
set -x

env

. /usr/share/mkapp/functions

for arch in $ARCH; do
  rm -rf ivy
  set_env $arch
  ant_build clean-all publish
  dpkg-name target/*.deb
  if [ "$PUBLISH" ]; then
    publish_ivy ivy
    publish_debs
  fi

  if [ "$RELEASE" ]; then
    cd target
    APP=$(ls *.app)
    APP=${APP%.app}
    mv $APP.app ${APP}_${arch}.app
    zip ../${APP}_${arch}.zip ${APP}_${arch}.app
    cd -
    echo "::set-output name=APP_${arch}::${APP}_${arch}.zip"
  fi
done
